# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

name: Docker-build-AKS-deploy


# Don't run against PRs
pr: none

variables:
  - name: repository
    value: 'webimage'
  - name: dockerfile
    value: '$(Build.SourcesDirectory)/Dockerfile'
  - name: containerRegistry
    value: 'ACR'

stages :
  - stage: Build
    displayName: Build and push to ACR
    jobs:  
    - job: Build
      displayName: Build job
      steps:
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          containerRegistry: ${{ variables.containerRegistry }}
          command: buildAndPush
          repository: ${{ variables.repository }}
          Dockerfile: ${{ variables.dockerfile }}
          tags: latest
