apiVersion: apps/latest
kind: Deployment
metadata:
  name: phaseone-app-deployment
spec:
  selector:
    matchLabels:
      app: phaseone-app
  template:
    metadata:
      labels:
        app: phaseone-app
    spec:
      containers:
      - name: prayashiimage
        image: epamacr.azurecr.io/webimage:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "1000m"
        ports:
        - containerPort: 80
